spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb3
    driver-class-name: org.mariadb.jdbc.Driver
    username: testuser3
    password: 123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


